---
title: "Citations"
output:
  html_document:
    theme: cosmo
---
### Citations

* Team, D. S. T. (2021, September 13). How to Round Data Frame Containing Character Variables in R. Universe of Data Science. Retrieved March 16, 2023, from https://universeofdatascience.com/how-to-round-data-frame-containing-character-variables-in-r/#more-913 

* Christophe Dervieux, Yihui Xie, & Emily Riederer. (2022, November 7). R Markdown Cookbook. 7.6 Put content in tabs. Retrieved March 16, 2023, from https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html 

* RStudio Shiny Master's Thesis Showcase. RStudio Shiny Gallery, RStudio, https://shiny.rstudio.com/gallery/masters.html. Accessed 13 April 2023.

* Shiny Gallery. RStudio Shiny Gallery, RStudio, https://shiny.rstudio.com/gallery/. Accessed 13 April 2023.

* Widget Gallery. RStudio Shiny Gallery, RStudio, https://shiny.rstudio.com/gallery/widget-gallery.html. Accessed 13 April 2023.

* Navbar Example. RStudio Shiny Gallery, RStudio, https://shiny.rstudio.com/gallery/navbar-example.html. Accessed 13 April 2023.

* Pork Chop. "R Shiny input slider range values." StackOverflow. https://stackoverflow.com/questions/38181744/r-shiny-input-slider-range-values. Accessed 13 April 2023.

* Robinson, Loan Kim. "Footer of the Application." Mastering Shiny, 1st ed., Chapman and Hall/CRC, 2020, https://bookdown.org/loankimrobinson/rshinybook/footer-of-the-application.html. Accessed 13 April 2023.

* "R Range Slider." Plotly, https://plotly.com/r/range-slider/. Accessed 13 April 2023.

* SBista. "Resize shiny wellPannel to contents and place a close button." StackOverflow. https://stackoverflow.com/questions/51659266/resize-shiny-wellpanel-to-contents-and-place-a-close-button. Accessed 13 April 2023.