---
title: "Final Dashboard"
author: "Kevin Ma"
date: "3-30-2023"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
    code_folding: hide
---

## Note: I tried setting the outline in the code to the correct color and could not figure out why it was not applying but the fill would apply correctly. I intend to go to OH to fix this if my group ends up using these boxplots.

# Report Dependencies and Setup Data
```{r message=FALSE}
library(tidyverse)
library(ggplot2)
library(reshape2)
library(skimr)
library(pollster)
library(kableExtra)
library(plotly)
library(shiny)
library(markdown)
```

```{r}
playoffs <- read.csv('2021-2022 NBA Player Stats - Playoffs.csv')
regular <- read.csv('2021-2022 NBA Player Stats - Regular.csv')

# Box plot 1 shows the amount of games each position plays
regular_b1<-regular %>%
  select(Pos, G) %>% # we only need these two columns
  rename(Position = Pos, Games_Played = G)

# Box plot 2 shows the minutes played per game by each position
regular_b2<-regular %>%
  select(Pos, MP) %>% # we only need these two columns
  rename(Position = Pos, Minutes_Played_Per_Game = MP)

```

```{r}
# Define UI
ui <- navbarPage("DS2003: Final Dashboard",
                 tabPanel("Home",
                            fillPage(
                            includeMarkdown("Home.rmd")
        )),
                tabPanel("Data"), # Not finished Fill in UI for this 
                tabPanel("EDA"), # Not finished Fill in UI for this 
                 navbarMenu("Questions",
                            tabPanel("Question 1",
                                     #fillPage(
                                       #includeMarkdown("Q1.rmd"),
        ),
                                     fluidPage(
                                       wellPanel(
                selectInput("view", label="Graph:",
                            choices = list("PPG, RPG, APG"=1, 
                            "Points Per Game"=2,
                            "Rebounds Per Game"=3,
                            "Assists Per Game"=4),
                            selected = 1),
                ),
      conditionalPanel(
        condition = "input.view == 1",
        plotOutput('allplots')
      ),
      conditionalPanel(
        condition = "input.view == 2",
        plotOutput('ppg')
      ),
      conditionalPanel(
        condition = "input.view == 3",
        plotOutput('rpg')
      ),
      conditionalPanel(
        condition = "input.view == 4",
        plotOutput('apg')
      )
      )),
                            tabPanel("Question 2",
                                     #fillPage(
                                       #includeMarkdown("Q2.rmd"),
        ),
                                     fluidRow(
                                       column(6, 
      plotlyOutput("boxplot_main"), 
      checkboxInput("outliers", "Toggle Boxpoints"),
      checkboxInput("boxmean", "Toggle Mean/SD", FALSE),
      checkboxInput("filter", "Filter Boxplots with < 5 Points")),
                                       column(6, 
      plotlyOutput("boxplot_main2"),
      checkboxInput("outliers2", "Toggle Boxpoint"),
      checkboxInput("boxmean2", "Toggle Mean/SD", FALSE),
      checkboxInput("filter2", "Filter Boxplots with < 5 Points"))))),
                  tabPanel("Summary",
                            fillPage(
                            includeMarkdown("Summary.rmd")
        )),
                  tabPanel("Citations",
                            fillPage(
                            includeMarkdown("Citations.rmd")
        )),
      )


# Define server
server <- function(input, output) {

      output$ppg <- renderPlot({
        ggplot(nba_pivot, aes(Player, regular, color = "Regular")) +
        geom_point(aes(shape = Stat), size =3) +
        geom_point(aes(Player, playoffs, color = "Playoff", shape = Stat), size = 3, alpha = 0.6) +
        scale_shape_manual(name = "Averages", values = c("PPG" = 19)) +
        scale_color_manual(name = "Season", values = c("Regular" = "#4EBCB6", "Playoff" = "#2E6039")) +
        labs(title = "Regular Season vs Playoff Season Average PPG", caption = 
        "Kaggle, 2021-2022 NBA Player Stats") +
        labs(x = "Player", y ="Points Per Game") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 15))
      })

      output$rpg <- renderPlot({
        ggplot(nba_pivot, aes(Player, regular, color = "Regular")) +
        geom_point(aes(shape = Stat), size =3) +
        geom_point(aes(Player, playoffs, color = "Playoff", shape = Stat), size = 3, alpha = 0.6) +
          ylim(0,20)+
        scale_shape_manual(name = "Averages", values = c("RPG" = 15)) +
        scale_color_manual(name = "Season", values = c("Regular" = "#4EBCB6", "Playoff" = "#2E6039")) +
        labs(title = "Regular Season vs Playoff Season Average RPG", caption = 
        "Kaggle, 2021-2022 NBA Player Stats") +
        labs(x = "Player", y ="Rebounds Per Game") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 15))
      })
      
      output$apg <- renderPlot({
        ggplot(nba_pivot, aes(Player, regular, color = "Regular")) +
        geom_point(aes(shape = Stat), size = 3) +
        geom_point(aes(Player, playoffs, color = "Playoff", shape = Stat), size = 3, alpha = 0.6) +
          ylim(0,15)+
        scale_shape_manual(name = "Averages", values = c("APG" = 17)) +
        scale_color_manual(name = "Season", values = c("Regular" = "#4EBCB6", "Playoff" = "#2E6039")) +
        labs(title = "Regular Season vs Playoff Season Average APG", caption = 
        "Kaggle, 2021-2022 NBA Player Stats") +
        labs(x = "Player", y ="Assists Per Game") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 15))
      })      

      output$allplots <- renderPlot({
        ggplot(nba_pivot, aes(Player, regular, color = "Regular")) +
        geom_point(aes(shape = Stat), size = 3) +
        geom_point(aes(Player, playoffs, color = "Playoff", shape = Stat), size = 3, alpha = 0.6) +
        facet_grid(Stat ~ ., scales = "free_y") +
        scale_shape_manual(name = "Averages", values = c("PPG" = 19, "APG" = 17, "RPG" = 15)) +
        scale_color_manual(name = "Season", values = c("Regular" = "#4EBCB6", "Playoff" = "#2E6039")) +
        labs(title = "Regular Season vs Playoff Season Averages", caption = 
        "Kaggle, 2021-2022 NBA Player Stats") +
        labs(x = "Player", y ="") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 15))
      })
  options = list(height = 800)

  # Create initial plot 1
  output$boxplot_main <- renderPlotly({
    plot_ly(regular_b1, x = ~Position, y = ~Games_Played, type = 'box',
            fillcolor='#2E603980', line=list(color='#0B1D5180'),
            boxpoints = 'all', jitter = 0.3,
            marker=list(color='#2E603980')) %>%
      layout(title = 'Games Played Based on Position',
             xaxis = list(title = 'Position'),
             yaxis = list(title = 'Games Played'))
  })
  
  # Update plot 1 based on checkbox input
  observeEvent(input$filter, {
    if (input$filter) {
      # Filter out boxplots with < 5 points
      filtered_b1 <- regular_b1 %>%
        group_by(Position) %>%
        filter(n() > 5)
      
      # Update plot 1
      output$boxplot_main <- renderPlotly({
        plot_ly(filtered_b1, x = ~Position, y = ~Games_Played, type = 'box', boxpoints = ifelse(input$outliers, "all", FALSE), boxmean = ifelse(input$boxmean, "sd", FALSE),
                fillcolor='#2E603980', line=list(color='#0B1D5180'),
                boxpoints = 'all', jitter = 0.3,
                marker=list(color='#2E603980')) %>%
          layout(title = 'Games Played Based on Position',
                 xaxis = list(title = 'Position'),
                 yaxis = list(title = 'Games Played'))
      })
    } else {
      # Reset plot 1 to initial state
      output$boxplot_main <- renderPlotly({
        plot_ly(regular_b1, x = ~Position, y = ~Games_Played, type = 'box', boxpoints = ifelse(input$outliers, "all", FALSE), boxmean = ifelse(input$boxmean, "sd", FALSE),
                fillcolor='#2E603980', line=list(color='#0B1D5180'),
                boxpoints = 'all', jitter = 0.3,
                marker=list(color='#2E603980')) %>%
          layout(title = 'Games Played Based on Position',
                 xaxis = list(title = 'Position'),
                 yaxis = list(title = 'Games Played'))
      })
    }
  })
   # Create initial plot 2
  output$boxplot_main2 <- renderPlotly({
    plot_ly(regular_b2, x = ~Position, y = ~Minutes_Played_Per_Game, type = 'box',
            fillcolor='#4EBCB680', line =list(color='#0B1D5180'),
            boxpoints = 'all', jitter = 0.3,
            marker=list(color='#4EBCB680')) %>%
      layout(title = 'Minutes Played Per Game Based on Position',
             xaxis = list(title = 'Position'),
             yaxis = list(title = 'Minutes Played per Game'))
  })
  # Update plot based on checkbox input
  observeEvent(input$filter2, {
    if (input$filter2) {
      # Filter out boxplots with < 5 points
      filtered_b2 <- regular_b2 %>%
        group_by(Position) %>%
        filter(n() > 5)
      
      # Update plot 2
      output$boxplot_main2 <- renderPlotly({
        plot_ly(filtered_b2, x = ~Position, y = ~Minutes_Played_Per_Game, type = 'box',
                fillcolor ='#4EBCB680', line =list(color='#0B1D5180'),
                boxpoints = ifelse(input$outliers2, "all", FALSE),
                boxmean = ifelse(input$boxmean2, "sd", FALSE),
                boxpoints = 'all', jitter = 0.3,
                marker=list(color='#4EBCB680')) %>%
          layout(title = 'Minutes Played Per Game Based on Position',
                 xaxis = list(title = 'Position'),
                 yaxis = list(title = 'Minutes Played per Game'))
      })
    } else {
      # Reset plot 2 to initial state
      output$boxplot_main2 <- renderPlotly({
        plot_ly(regular_b2, x = ~Position, y = ~Minutes_Played_Per_Game, type = 'box',
                fillcolor='#4EBCB680', line=list(color='#0B1D5180'),
                boxpoints = ifelse(input$outliers2, "all", FALSE),
                boxmean = ifelse(input$boxmean2, "sd", FALSE),
                boxpoints = 'all', jitter = 0.3,
                marker=list(color='#4EBCB680')) %>%
          layout(title = 'Minutes Played Per Game Based on Position',
                 xaxis = list(title = 'Position'),
                 yaxis = list(title = 'Minutes Played per Game'))
      })
    }
  })
}


# Run the app
shinyApp(ui, server)  
```

Reorganized dataframes
```{r warning=FALSE}
# Combine playoffs and regular season with .playoffs or .regular as distinctions
nba <- playoffs %>%
  left_join(regular, by="Player", suffix = c(".playoffs", ".regular"))
  
nba <- playoffs %>%
  left_join(regular, by="Player", suffix = c(".playoffs", ".regular"))
# filter to only include nba players who average more than:
# top15th leader in ppg in the regular or playoff or
# top15th leader in pg in the regular or playoff or
# top15th leader in apg in the regular or playoff
nba_filtered <- nba %>%
  group_by(Player) %>%
  summarize(
    PPG_regular = round(mean(PTS.regular, na.rm = TRUE), 2),
    RPG_regular = round(mean(TRB.regular, na.rm = TRUE), 2),
    APG_regular = round(mean(AST.regular, na.rm = TRUE), 2),
    PPG_playoffs = round(mean(PTS.playoffs, na.rm = TRUE), 2),
    RPG_playoffs = round(mean(TRB.playoffs, na.rm = TRUE), 2),
    APG_playoffs = round(mean(AST.playoffs, na.rm = TRUE), 2)
  ) %>%
  filter(
    PPG_regular >= 24.6 | PPG_playoffs >= 22.8 |
    RPG_regular >= 10.1 | RPG_playoffs >= 7.6 |
    APG_regular >= 7 | APG_playoffs >= 5.9
  )
# Manually fix players who have accents in their name
nba_filtered$Player[22] <- "Jonas Valanciunas"
nba_filtered$Player[30] <- "Luka Doncic"
nba_filtered$Player[32] <- "Nikola Jokic"
nba_filtered$Player[33] <- "Nikola Vucevic"

# tidy format that can be plotted with ggplot
nba_tidy <- nba_filtered %>%
  select(Player, PPG_regular, RPG_regular, APG_regular, PPG_playoffs, RPG_playoffs, APG_playoffs) %>%
  gather(key, value, -Player) %>%
  separate(key, into = c("Attribute", "Season"), sep = "_") %>%
  spread(Season, value)

# pivot the data to a wide format that can be used with geom_point()
nba_pivot<- nba_tidy %>%
  pivot_longer(cols = c("regular", "playoffs"), names_to = "Season", values_to = "amount") %>%
  separate(Attribute, into = c("Stat", "Type"), sep = "_") %>%
  pivot_wider(names_from = Season, values_from = amount)
# set the levels in desired order
nba_pivot$Stat <- factor(nba_pivot$Stat, levels = c("PPG", "RPG", "APG"))
```